src/objects/Credential_Export__c.object
<CustomObject>
    <fields>
        <fullName>Date_Requested__c</fullName>
        <label>Date Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Vehicle</fullName>
                </value>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credential Export</label>
    <nameField>
        <displayFormat>CE - {0000}</displayFormat>
        <label>Credential Export Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MTM_CredentialingExportController.cls
/***********************************************************************
Apex Class          : MTM_CredentialingExportController
Author                      : Chaitanya M
Created Date                : 18 September 2018
Descritption                : This Apex class is used to display credentialing export records with new insert functionlity.

Change History:

Date            Modified By         Change Made
9/18/2018       Chaitanya M     
************************************************************************/ 
public class MTM_CredentialingExportController {

    @AuraEnabled
    public static List<Credential_Export__c> getRecords() {
        List<Credential_Export__c> credentialsExport = new List<Credential_Export__c>();
        
        credentialsExport = [
            SELECT Id, Name, End_Date__c, Object_Type__c, Plan_Code__c, Start_Date__c, Status__c, Date_Requested__c
            FROM Credential_Export__c
        ];
        return credentialsExport;
    }
}